from ComputerPyGraphics import CG

cg = CG(20, 20, ".")

print("Enter the value of x1: ")
x1 = int(input())
print("Enter the value of y1: ")
y1 = int(input())
print("Enter the value of x2: ")
x2 = int(input())
print("Enter the value of y2: ")
y2 = int(input())

dx = x2-x1
dy = y2-y1

d = 2*dy - dx

xi = x1
yi = y1

while xi != x2 and yi != y2:
    cg.putpixel(xi, yi)
    if d < 0:
        d = d + 2 * dy
        xi += 1
    else:
        d = d + 2 * dy - 2 * dx
        xi += 1
        yi += 1

cg.show()

##################################
# OUTPUT
# Enter the value of x1:
# 2
# Enter the value of y1:
# 5
# Enter the value of x2:
# 8
# Enter the value of y2:
# 8
# .....................
# .....................
# .....................
# ...............@@....
# .............@@......
# ............@........
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
# .....................
